### ISSUE TITLE
Does ToCa support using FA?

### ISSUE THREAD

**Issue by Edwardmark** [Shenyi-Z/ToCa#2]
Thanks for your great work.
Does ToCa support using FA? In the open-sora demo config, the FA config is set to False. So does ToCa support FA?

**Comment by Shenyi-Z** [comment]
Thanks for your focus! Not yet, the key problem is we need the attention map for scores, and it's not easy to gain from FA. Perhaps we need to tweak the FA source code a bit to do this, it's actually relatively simple and maybe we'll do it when conditions allow.

**Comment by Shenyi-Z** [comment]
Thank you for your attention! In the OpenSora(-ToCa) model, FA is supported, but only for Spatial and Temporal attention. FA isn't used for cross-attention because we need to extract the attention map. Additionally, in our two image models, DiT-ToCa and PixArt-alpha-ToCa, the DiT version does not support FA due to the need to extract DiT's attention map for scoring. The current PixArt-alpha-ToCa does support it, as it only uses cross-attention for scoring, but it requires some minor adjustments.

The key reason FA cannot be used with ToCa in some cases is that we need to extract the attention map for scoring in certain scenarios. This isn't a major issue and can be resolved by tweaking the FA code, which we plan to do as conditions allow.

**Comment by Edwardmark** [comment]
> Spatial and Temporal

But as the paper says, ToCa also need the self-attention scores, so how to support FA for Spatial and Temporal Attention? They are all self-attention.

**Comment by Shenyi-Z** [comment]
Yes, but in practice, our approach on OpenSora usually sets the self-attention weights to zero, so it's not needed in that case. To make FA support extracting the attention map, we might need to modify the source code of their module.

**Comment by Edwardmark** [comment]
> Yes, but in practice, our approach on OpenSora usually sets the self-attention weights to zero, so it's not needed in that case. To make FA support extracting the attention map, we might need to modify the source code of their module.

Thanks for your kind reply. So in practice, using only cross attention score without self-attention score can get decent result? Is that right?

**Comment by Shenyi-Z** [comment]
Absolutely!
